### ISSUE TITLE
Plugin seems to crash on OnActivate

### ISSUE THREAD

**Issue by jperezrod** [mattermost/mattermost-plugin-gitlab#230]
When trying to enable the plugin it fails, and I can see in Plugin Management the error:
`This plugin crashed multiple times and is no longer running. Check your system logs for errors.`

The versions used are:

* Mattermost Version: 5.29.0
* com.github.manland.mattermost-plugin-gitlab - 1.2.0

Mattermost has been installing using docker-compose.

When enabling the plugin with DEBUG logging enable I get the following logs:

```
{"level":"debug","ts":1605780815.4952419,"caller":"plugin/hclog_adapter.go:51","msg":"starting plugin","plugin_id":"com.github.manland.mattermost-plugin-gitlab","wrapped_extras":"path/mattermost/plugins/com.github.manland.mattermost-plugin-gitlab/server/dist/plugin-linux-amd64args[/mattermost/plugins/com.github.manland.mattermost-plugin-gitlab/server/dist/plugin-linux-amd64]"}
{"level":"debug","ts":1605780815.497304,"caller":"plugin/hclog_adapter.go:51","msg":"plugin started","plugin_id":"com.github.manland.mattermost-plugin-gitlab","wrapped_extras":"path/mattermost/plugins/com.github.manland.mattermost-plugin-gitlab/server/dist/plugin-linux-amd64pid20008"}
{"level":"debug","ts":1605780815.4973586,"caller":"plugin/hclog_adapter.go:51","msg":"waiting for RPC address","plugin_id":"com.github.manland.mattermost-plugin-gitlab","wrapped_extras":"path/mattermost/plugins/com.github.manland.mattermost-plugin-gitlab/server/dist/plugin-linux-amd64"}
{"level":"debug","ts":1605780815.50775,"caller":"plugin/hclog_adapter.go:51","msg":"using plugin","plugin_id":"com.github.manland.mattermost-plugin-gitlab","wrapped_extras":"version1"}
{"level":"debug","ts":1605780815.5080462,"caller":"plugin/hclog_adapter.go:51","msg":"plugin address","plugin_id":"com.github.manland.mattermost-plugin-gitlab","wrapped_extras":"address/tmp/plugin720920173networkunixtimestamp2020-11-19T10:13:35.507Z"}
{"level":"debug","ts":1605780815.563832,"caller":"plugin/hclog_adapter.go:53","msg":"panic: runtime error: invalid memory address or nil pointer dereference","plugin_id":"com.github.manland.mattermost-plugin-gitlab"}
{"level":"debug","ts":1605780815.563876,"caller":"plugin/hclog_adapter.go:53","msg":"[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0xba40c1]","plugin_id":"com.github.manland.mattermost-plugin-gitlab"}
{"level":"debug","ts":1605780815.5638888,"caller":"plugin/hclog_adapter.go:53","msg":"","plugin_id":"com.github.manland.mattermost-plugin-gitlab"}
{"level":"debug","ts":1605780815.5639105,"caller":"plugin/hclog_adapter.go:53","msg":"goroutine 20 [running]:","plugin_id":"com.github.manland.mattermost-plugin-gitlab"}
{"level":"debug","ts":1605780815.5639215,"caller":"plugin/hclog_adapter.go:53","msg":"main.(*Plugin).OnActivate(0xc00030de30, 0xde5b20, 0xc00030de30)","plugin_id":"com.github.manland.mattermost-plugin-gitlab"}
{"level":"debug","ts":1605780815.5639315,"caller":"plugin/hclog_adapter.go:53","msg":"\t/home/circleci/project/server/plugin.go:86 +0x5a1","plugin_id":"com.github.manland.mattermost-plugin-gitlab"}
{"level":"debug","ts":1605780815.5639496,"caller":"plugin/hclog_adapter.go:53","msg":"github.com/mattermost/mattermost-server/v5/plugin.(*hooksRPCServer).OnActivate(0xc00000ec60, 0xc00024a32c, 0xc0002e43c0, 0x0, 0x0)","plugin_id":"com.github.manland.mattermost-plugin-gitlab"}
{"level":"debug","ts":1605780815.563967,"caller":"plugin/hclog_adapter.go:53","msg":"\t/go/pkg/mod/github.com/mattermost/mattermost-server/v5@v5.25.1/plugin/client_rpc.go:228 +0x1d1","plugin_id":"com.github.manland.mattermost-plugin-gitlab"}
{"level":"debug","ts":1605780815.5639775,"caller":"plugin/hclog_adapter.go:53","msg":"reflect.Value.call(0xc000079ce0, 0xc000010568, 0x13, 0xdfbbb7, 0x4, 0xc00005cf08, 0x3, 0x3, 0x0, 0x0, ...)","plugin_id":"com.github.manland.mattermost-plugin-gitlab"}
{"level":"debug","ts":1605780815.5639875,"caller":"plugin/hclog_adapter.go:53","msg":"\t/usr/local/go/src/reflect/value.go:460 +0x8ab","plugin_id":"com.github.manland.mattermost-plugin-gitlab"}
{"level":"debug","ts":1605780815.5639966,"caller":"plugin/hclog_adapter.go:53","msg":"reflect.Value.Call(0xc000079ce0, 0xc000010568, 0x13, 0xc00004af08, 0x3, 0x3, 0x0, 0x0, 0x0)","plugin_id":"com.github.manland.mattermost-plugin-gitlab"}
{"level":"debug","ts":1605780815.564006,"caller":"plugin/hclog_adapter.go:53","msg":"\t/usr/local/go/src/reflect/value.go:321 +0xb4","plugin_id":"com.github.manland.mattermost-plugin-gitlab"}
{"level":"debug","ts":1605780815.564016,"caller":"plugin/hclog_adapter.go:53","msg":"net/rpc.(*service).call(0xc000076cc0, 0xc00007a460, 0xc000038b70, 0xc000038b80, 0xc000302c00, 0xc00000f7e0, 0xc1aa40, 0xc00024a32c, 0x16, 0xc1aa80, ...)","plugin_id":"com.github.manland.mattermost-plugin-gitlab"}
{"level":"debug","ts":1605780815.5640266,"caller":"plugin/hclog_adapter.go:53","msg":"\t/usr/local/go/src/net/rpc/server.go:377 +0x17f","plugin_id":"com.github.manland.mattermost-plugin-gitlab"}
{"level":"debug","ts":1605780815.564036,"caller":"plugin/hclog_adapter.go:53","msg":"created by net/rpc.(*Server).ServeCodec","plugin_id":"com.github.manland.mattermost-plugin-gitlab"}
{"level":"debug","ts":1605780815.564046,"caller":"plugin/hclog_adapter.go:53","msg":"\t/usr/local/go/src/net/rpc/server.go:474 +0x42b","plugin_id":"com.github.manland.mattermost-plugin-gitlab"}
{"level":"error","ts":1605780815.5694282,"caller":"mlog/log.go:229","msg":"RPC call to OnActivate plugin failed.","plugin_id":"com.github.manland.mattermost-plugin-gitlab","error":"unexpected EOF"}
```

Sorry in advance if this is a configuration error on my side.

**Comment by hanzei** [comment]
@jperezrod Do you have a SiteURL set in your config file?

**Comment by hanzei** [comment]
@jperezrod I've submitted https://github.com/mattermost/mattermost-plugin-gitlab/pull/231 as a proper fix. The workaround is to get a SiteURL in the System Console, which you should do anyway.

**Comment by jperezrod** [comment]
@hanzei thanks for the hint, setting up the Site URL in the System Console made it work.
