### ISSUE TITLE
gitlab command crashed the com.github.mainland.mattermost-plugin-gitlab plugin. Please contact your system administrator

### ISSUE THREAD

**Issue by xueyu888** [mattermost/mattermost-plugin-gitlab#516]
![image](https://github.com/user-attachments/assets/d6b79925-139f-460d-8040-64ab9c90d12f)

When I try to subscribe using GitLab, I encounter this error. 

However, when I directly configure the specific repository address, it works. After configuring the webhook, the GitLab test passes, displaying "Hook executed successfully: HTTP 200." Despite this, there are no notifications on Mattermost.

**Comment by xueyu888** [comment]
To add, the error occurred when I clicked “execute current command”

**Comment by xueyu888** [comment]
This is my docker logs:
```
{"timestamp":"2024-08-10 02:51:26.145 Z","level":"warn","msg":"Recovered from a panic","caller":"app/plugin_api.go:1006","plugin_id":"com.github.manland.mattermost-plugin-gitlab","Command":"/gitlab subscriptions add","UserId":"u567pgtpitfxux38ojkq7k33xe","error":"runtime error: index out of range [1] with length 1","stack":"goroutine 504 [running]:\nruntime/debug.Stack()\n\truntime/debug/stack.go:24 +0x5e\nmain.(*Plugin).ExecuteCommand.func1()\n\tgithub.com/mattermost/mattermost-plugin-gitlab/server/command.go:155 +0x5d\npanic({0xdcebc0?, 0xc0004e6a38?})\n\truntime/panic.go:920 +0x270\nmain.(*Plugin).subscribeCommand(0xc000696020?, {0xfbc748, 0xc000266310}, {0xc0008a5910?, 0x0?, 0x18?}, {0xc000696040, 0x1a}, 0xc000366380, 0xc00079f140)\n\tgithub.com/mattermost/mattermost-plugin-gitlab/server/command.go:673 +0x26a\nmain.(*Plugin).ExecuteCommand(0xc00039d5f0, 0xe430c0?, 0xc00030c3c0)\n\tgithub.com/mattermost/mattermost-plugin-gitlab/server/command.go:226 +0x1697\ngithub.com/mattermost/mattermost/server/public/plugin.(*hooksRPCServer).ExecuteCommand(0x2?, 0xc0003fa2d0, 0xc0003fa470)\n\tgithub.com/mattermost/mattermost/server/public@v0.0.9-0.20230830065520-5de1e306de52/plugin/client_rpc_generated.go:114 +0x52\nreflect.Value.call({0xc000794480?, 0xc0000bc438?, 0x13?}, {0xe5404b, 0x4}, {0xc000383ef8, 0x3, 0x3?})\n\treflect/value.go:596 +0xce7\nreflect.Value.Call({0xc000794480?, 0xc0000bc438?, 0xc000838e80?}, {0xc000838ef8?, 0xfb3940?, 0x6da460?})\n\treflect/value.go:380 +0xb9\nnet/rpc.(*service).call(0xc0002fc0c0, 0xc000468240?, 0xc00046a080?, 0xc0002e00c0, 0xc0002b0280, 0xc000838e50?, {0xc46920?, 0xc0003fa2d0?, 0x6d7d25?}, {0xc46960, ...}, ...)\n\tnet/rpc/server.go:382 +0x211\ncreated by net/rpc.(*Server).ServeCodec in goroutine 30\n\tnet/rpc/server.go:479 +0x410\n"}
{"timestamp":"2024-08-10 02:51:26.160 Z","level":"error","msg":"RPC call ExecuteCommand to plugin failed.","caller":"plugin/client_rpc_generated.go:104","plugin_id":"com.github.manland.mattermost-plugin-gitlab","error":"unexpected EOF"}
{"timestamp":"2024-08-10 02:51:26.161 Z","level":"error","msg":"/gitlab command crashed the com.github.manland.mattermost-plugin-gitlab plugin. Please contact your system administrator","caller":"web/context.go:115","path":"/api/v4/commands/execute","request_id":"wz948nhapig4dbs3o6gdktow7y","ip_addr":"192.168.115.66","user_id":"u567pgtpitfxux38ojkq7k33xe","method":"POST","err_where":"ExecutePluginCommand","http_code":500,"error":"ExecutePluginCommand: /gitlab command crashed the com.github.manland.mattermost-plugin-gitlab plugin. Please contact your system administrator, err= Plugin com.github.manland.mattermost-plugin-gitlab crashed due to /gitlab command"}
{"timestamp":"2024-08-10 02:51:26.161 Z","level":"error","msg":"plugin process exited","caller":"plugin/hclog_adapter.go:79","plugin_id":"com.github.manland.mattermost-plugin-gitlab","wrapped_extras":"pluginplugins/com.github.manland.mattermost-plugin-gitlab/server/dist/plugin-linux-amd64id53errorexit status 2"}
{"timestamp":"2024-08-10 02:51:46.814 Z","level":"warn","msg":"Health check failed for plugin","caller":"plugin/health_check.go:59","id":"com.github.manland.mattermost-plugin-gitlab","error":"plugin RPC connection is not responding"}
{"timestamp":"2024-08-10 02:51:46.814 Z","level":"error","msg":"RPC call OnDeactivate to plugin failed.","caller":"plugin/client_rpc_generated.go:33","plugin_id":"com.github.manland.mattermost-plugin-gitlab","error":"connection is shut down"}
{"timestamp":"2024-08-10 02:51:46.814 Z","level":"warn","msg":"error closing client during Kill","caller":"plugin/hclog_adapter.go:70","plugin_id":"com.github.manland.mattermost-plugin-gitlab","wrapped_extras":"errconnection is shut down"}
{"timestamp":"2024-08-10 02:51:46.814 Z","level":"warn","msg":"plugin failed to exit gracefully","caller":"plugin/hclog_adapter.go:72","plugin_id":"com.github.manland.mattermost-plugin-gitlab"}
{"timestamp":"2024-08-10 02:53:22.192 Z","level":"info","msg":"SimpleWorker: Job is complete","caller":"jobs/base_workers.go:101","worker_name":"ExpiryNotify","job_id":"8nizrht4u7yptdzp6pn6n7jt1y","job_type":"expiry_notify","job_create_at":"Aug 10 02:53:16.452"}
{"timestamp":"2024-08-10 02:54:52.121 Z","level":"warn","msg":"Recovered from a panic","caller":"app/plugin_api.go:1006","plugin_id":"com.github.manland.mattermost-plugin-gitlab","Command":"/gitlab subscriptions add","UserId":"u567pgtpitfxux38ojkq7k33xe","error":"runtime error: index out of range [1] with length 1","stack":"goroutine 195 [running]:\nruntime/debug.Stack()\n\truntime/debug/stack.go:24 +0x5e\nmain.(*Plugin).ExecuteCommand.func1()\n\tgithub.com/mattermost/mattermost-plugin-gitlab/server/command.go:155 +0x5d\npanic({0xdcebc0?, 0xc000715410?})\n\truntime/panic.go:920 +0x270\nmain.(*Plugin).subscribeCommand(0xc00058a120?, {0xfbc748, 0xc000224e70}, {0xc0001c5850?, 0x0?, 0x18?}, {0xc00058a140, 0x1a}, 0xc000316100, 0xc000779a40)\n\tgithub.com/mattermost/mattermost-plugin-gitlab/server/command.go:673 +0x26a\nmain.(*Plugin).ExecuteCommand(0xc000672680, 0xe430c0?, 0xc0006e2460)\n\tgithub.com/mattermost/mattermost-plugin-gitlab/server/command.go:226 +0x1697\ngithub.com/mattermost/mattermost/server/public/plugin.(*hooksRPCServer).ExecuteCommand(0x2?, 0xc000730210, 0xc000730350)\n\tgithub.com/mattermost/mattermost/server/public@v0.0.9-0.20230830065520-5de1e306de52/plugin/client_rpc_generated.go:114 +0x52\nreflect.Value.call({0xc00043a720?, 0xc000438068?, 0x13?}, {0xe5404b, 0x4}, {0xc0005acef8, 0x3, 0x3?})\n\treflect/value.go:596 +0xce7\nreflect.Value.Call({0xc00043a720?, 0xc000438068?, 0xcfd480?}, {0xc000425ef8?, 0xc00016a7d0?, 0xc000425f50?})\n\treflect/value.go:380 +0xb9\nnet/rpc.(*service).call(0xc0002620c0, 0xc000168180?, 0xc000437300?, 0xc000144170, 0xc000436280, 0xc000425f18?, {0xc46920?, 0xc000730210?, 0xc000168180?}, {0xc46960, ...}, ...)\n\tnet/rpc/server.go:382 +0x211\ncreated by net/rpc.(*Server).ServeCodec in goroutine 83\n\tnet/rpc/server.go:479 +0x410\n"}
{"timestamp":"2024-08-10 02:54:52.133 Z","level":"error","msg":"RPC call ExecuteCommand to plugin failed.","caller":"plugin/client_rpc_generated.go:104","plugin_id":"com.github.manland.mattermost-plugin-gitlab","error":"unexpected EOF"}
{"timestamp":"2024-08-10 02:54:52.133 Z","level":"error","msg":"/gitlab command crashed the com.github.manland.mattermost-plugin-gitlab plugin. Please contact your system administrator","caller":"web/context.go:115","path":"/api/v4/commands/execute","request_id":"ujkhrzgn13roxjzjx3xrzmd3nh","ip_addr":"192.168.115.66","user_id":"u567pgtpitfxux38ojkq7k33xe","method":"POST","err_where":"ExecutePluginCommand","http_code":500,"error":"ExecutePluginCommand: /gitlab command crashed the com.github.manland.mattermost-plugin-gitlab plugin. Please contact your system administrator, err= Plugin com.github.manland.mattermost-plugin-gitlab crashed due to /gitlab command"}
{"timestamp":"2024-08-10 02:54:52.133 Z","level":"error","msg":"plugin process exited","caller":"plugin/hclog_adapter.go:79","plugin_id":"com.github.manland.mattermost-plugin-gitlab","wrapped_extras":"pluginplugins/com.github.manland.mattermost-plugin-gitlab/server/dist/plugin-linux-amd64id287errorexit status 2"}
{"timestamp":"2024-08-10 02:55:16.814 Z","level":"warn","msg":"Health check failed for plugin","caller":"plugin/health_check.go:59","id":"com.github.manland.mattermost-plugin-gitlab","error":"plugin RPC connection is not responding"}
{"timestamp":"2024-08-10 02:55:16.814 Z","level":"error","msg":"RPC call OnDeactivate to plugin failed.","caller":"plugin/client_rpc_generated.go:33","plugin_id":"com.github.manland.mattermost-plugin-gitlab","error":"connection is shut down"}
{"timestamp":"2024-08-10 02:55:16.814 Z","level":"warn","msg":"error closing client during Kill","caller":"plugin/hclog_adapter.go:70","plugin_id":"com.github.manland.mattermost-plugin-gitlab","wrapped_extras":"errconnection is shut down"}
```
